# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3d462d0c764de280a83b9af55f91875ef19e91c2a768c7c0a4ae12945b2e22772846f1a5ce3e475d2502406f6b48c8f146e578b10a857f97102ed0b5952f672

test:
  secret_key_base: e1814b95444b98aeb8b2a77ea17eb4d9fe86be42861e6804c713606715d7a8f18aadcdc172240e3b0d16189f7aa1f1f3c396ee1be9811643967536e5e4d41878

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
